openapi: 3.2.0
info:
  description: '# Introduction

    Welcome to the Gravity Connect API documentation for Device Partners (typically Device OEMs).'
  x-logo:
    url: ./assets/vp_logo.png
    backgroundColor: '#FFFFFF'
    altText: Virtual Peaker Logo
  version: 2.0.6
  title: Gravity Connect API (Device Partner) Commands API
  license:
    name: BSD
servers:
- url: https://example.com
security:
- device_partner_api_auth:
  - device_partner_basic_auth
- device_partner_user_auth:
  - user_read
tags:
- name: Commands
  description: Command specific endpoints
paths:
  /command:
    post:
      summary: Send command
      operationId: sendCommand
      tags:
      - Commands
      security:
      - device_partner_api_auth:
        - basic_partner_read_write
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - targeting
              - uid
              - startTime
              - duration
              properties:
                targeting:
                  type: string
                  enum:
                  - group
                  - device
                uid:
                  type: string
                  description: Group or device uid
                kind:
                  $ref: '#/components/schemas/DeviceKindEnum'
                startTime:
                  type: string
                  format: date-time
                  description: For more see, [RFC 3339, section 5.6](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6). As an example, '2017-07-21T17:32:28Z'. The timezone is always zero UTC offset. A startTime in the past should still be considered valid if startTime + duration is still in the future
                duration:
                  type: integer
                  description: Length of event in seconds. The value should be greater than 0. If a device partner imposes a maximum event duration, frequently it is either 8 or 24 hours.
                command:
                  type: object
                  description: Varies by device kind, see documentation for VP_COMMAND_OBJECT
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                required:
                - refId
                properties:
                  refId:
                    type: string
                    description: A unique ID for that command within the partners system to be used when reading/reporting command state or cancelling
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Details'
  /command/{COMMAND_REFERENCE_ID}:
    get:
      summary: Read command state
      operationId: readCommandState
      tags:
      - Commands
      security:
      - device_partner_api_auth:
        - basic_partner_read_write
      parameters:
      - name: COMMAND_REFERENCE_ID
        in: path
        required: true
        description: The id of the command being read
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandState'
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Details'
    delete:
      summary: Cancel command
      operationId: cancelCommand
      tags:
      - Commands
      security:
      - device_partner_api_auth:
        - basic_partner_read_write
      parameters:
      - name: COMMAND_REFERENCE_ID
        in: path
        required: true
        description: The id of the command being cancelled
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandState'
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Details'
components:
  schemas:
    DeviceKindEnum:
      type: string
      enum:
      - HWH
      - TSTAT
      - BATTERY
      - EVSE
      - V2G
      - STORAGE-HVAC
    Details:
      type: object
      required:
      - message
      properties:
        message:
          type: string
          description: A human readable response. Because there's no standard for what is included or how information should be formatted, this should not be parsed and utilized programmatically.
    CommandState:
      type: object
      required:
      - state
      - time
      properties:
        state:
          type: string
          description: 'State of the command:

            * PENDING - scheduled but not started

            * IN_PROGRESS - when pending command hits start time

            * FAILED - something has prevented the command from being scheduled or started

            * OPT_OUT - device owner has specified that they don’t want to participate in an event

            * CANCELLED - utility has said they don’t want the event to happen

            * COMPLETED - end time of event has been reached without becoming CANCELLED or OPT_OUT'
          enum:
          - PENDING
          - IN_PROGRESS
          - FAILED
          - OPT_OUT
          - CANCELLED
          - COMPLETED
        description:
          type: string
          description: human readable status
        time:
          type: string
          format: date-time
          description: For more see, [RFC 3339, section 5.6](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6). As an example, '2017-07-21T17:32:28Z'. The timezone is always zero UTC offset.
        refId:
          type: string
          description: Command Reference ID
  responses:
    unauthorized:
      description: The request was not properly authorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Details'
    badRequest:
      description: Request was not properly formatted
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Details'
  securitySchemes:
    device_partner_api_auth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://example.com/oauth/token
          scopes:
            basic_partner_read_write: conducts all actions on the partners behalf
    device_partner_user_auth:
      type: oauth2
      description: If using the OAuth onboarding method, this authentication method is used for the respective endpoints. Please the the FAQ for more details.
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            user_read: read details about new user
x-tagGroups:
- name: Base Implementation
  tags:
  - Devices
  - Commands
  - Energy Interval Endpoint
- name: Device Onboarding
  tags:
  - OAuth Device Discovery (Preferred)
  - Pairing Code Device Discovery - End User App
  - Pairing Code Device Discovery - Utility Commissioned Installation
  - Device Partner Driven Enrollment
- name: Group Management
  tags:
  - Group Management
